name: modularapparchitecture
description: "Modular App Architecture Kit 2026 â€” Feature-first Flutter starter with GetX, clean architecture, Firebase helpers, and CLI generators."
repository: https://github.com/moazzamshah21/Modular-App-Architecture-Kit.git
homepage: https://github.com/moazzamshah21/Modular-App-Architecture-Kit
documentation: https://github.com/moazzamshah21/Modular-App-Architecture-Kit#readme
topics:
  - flutter
  - getx
  - architecture
  - firebase
  - cli

version: 0.1.1+2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  path: ^1.9.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

executables:
  modular_app:

flutter:
  uses-material-design: true
